// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgxmofqqqwqhqovuwfim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNneG1vZnFxcXdxaHFvdnV3ZmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzcwNTgsImV4cCI6MjA2NzAxMzA1OH0.VvHPa8WkM5d4MG2CRyzVphE4pzVU0VF9vMjBQiFkNH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});